/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _wii_jpg_h_
#define _wii_jpg_h_
//---------------------------------------------------------------------------------
extern const unsigned char wii_jpg[];
extern const int wii_jpg_size;
// User added parameters.
extern const int wii_jpg_width;
extern const int wii_jpg_height;
//---------------------------------------------------------------------------------
#endif //_wii_jpg_h_
//---------------------------------------------------------------------------------
